#!/bin/sh
#
# colorbars - smpte color bars in sh
# http://git.io/colorbars 
LC_ALL=C

echo

for y in $(seq 0 13); do
  printf %s '           '
  for color in 7 3 6 2 5 1 4; do
    printf '\033[4%dm%s' "$color" '        '
  done
  printf '\033[0m\n'
done

for y in 0 1; do
  printf %s '           '
  for color in 4 0 5 0 6 0 7; do
    printf '\033[4%dm%s' "$color" '        '
  done
  printf '\033[0m\n'
done

for y in $(seq 0 4); do
  printf %s '           '
  for color in 4 4 4 4 4 7 7 7 7 7 5 5 5 5 5 0 0 0 0 0 0 0 0 0 0 0 0 0; do
    printf '\033[4%dm%s' "$color" '  '
  done
  printf '\033[0m\n'
done

echo
